export let news = [
    {
        "id": 1,
        "category": "Technology",
        "title": "Breaking: Major Tech Company Announces Game-Changing Innovation",
        "post": "Posted by  Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global",
        "image": "https://newsportal.electronthemes-ghost.com/content/images/size/w2000/2024/09/2149037906.jpg",
        "title1": "The Unveiling of a New Era",
        "image1": "https://images.unsplash.com/photo-1725615357444-6123528686cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8YWxsfDQzfHx8fHx8Mnx8MTcyNTg4MTQzNXw&ixlib=rb-4.0.3&q=80&w=1000",
        "semititle1": "In a highly anticipated event streamed live to millions of viewers worldwide, the CEO of the tech giant took the stage to reveal the company’s latest innovation. The atmosphere was electric as the audience, composed of industry experts, investors, and tech enthusiasts, waited with bated breath. The presentation began with a retrospective look at the company’s history of innovation, highlighting previous breakthroughs that had set new standards in the industry.",
        "quote": "But it was clear that this announcement was different. The company’s leader spoke passionately about the future and the responsibility of tech companies",

    },
    {
        "id": 2,
        "category": "Technology",
        "title": "Electric Car Revolutionize the Auto Industry",
        "post": "Posted by  Jamie Larison",
        "date": "Sep 05, 2024",
        "semiTitle": "New Electric Car Models Set to Revolutionize the Auto Industry",
        "image": "https://images.unsplash.com/photo-1603724223241-527d8009e029?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDR8fCUyMEVsZWN0cmljJTIwQ2FyfGVufDB8fHx8MTcyNTUzMjY0N3ww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Unveiling of a New Era",
        "semititle1": "The automotive industry is undergoing a monumental transformation, driven by advancements in electric vehicle (EV) technology, environmental concerns, and shifting consumer preferences. As the world moves towards greener and more sustainable transportation solutions, several new electric car models are poised to revolutionize the industry. This article delves into some of the most exciting new electric car models set to make a significant impact in the near future.",

    },
    {
        "id": 3,
        "category": "Technology",
        "title": "Top 10 Emerging Technologies to Watch",
        "post": "Posted by  Enamul Haque",
        "date": "Sep 05, 2024",
        "semiTitle": "Climate change is a pressing global challenge with far-reaching implications, affecting not only the environment but also economic activities and international trade. As the planet warms and extreme weather events become more frequent, the patterns and dynamics of global trade are being significantly altered. This article explores how climate change is impacting international trade, examining its effects on supply chains, trade patterns, and global markets, and discussing the strategies businesses and governments are adopting to adapt to these changes.",
        "image": "https://images.unsplash.com/photo-1678799200184-a813e6039df1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDE4fHx0ZWN8ZW58MHx8fHwxNzI1NTM3ODM3fDA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "Disruption of Supply Chains",

        "semititle1": "One of the most immediate and visible impacts of climate change on international trade is the disruption of supply chains. Extreme weather events, such as hurricanes, floods, and heatwaves, can cause significant damage to infrastructure, halt production, and delay shipments.",

    },
    {
        "id": 4,
        "category": "Technology",
        "title": "The Future of Quantum Computing: What to Expect",
        "post": "Posted by Walter White",
        "date": "Sep 05, 2024",
        "semiTitle": "As we approach 2024, businesses and entrepreneurs face a rapidly evolving landscape marked by technological advancements, shifting consumer expectations, and global economic changes. Staying ahead of these trends is crucial for strategic planning and maintaining a competitive edge. This article explores the top five business trends shaping 2024, providing insights into how these developments will influence the business world and what organizations need to do to adapt.",
        "image": "https://images.unsplash.com/photo-1667984390538-3dea7a3fe33d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDQ5fHxRdWFudHVtJTIwQ29tcHV0aW5nfGVufDB8fHx8MTcyNTU4Njg2NHww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "Artificial Intelligence and Automation",
        "semititle1": "Advances in AI technologies, such as machine learning and natural language processing, are enabling businesses to harness data more effectively. In 2024, we can expect AI to play a critical role in predictive analytics, personalized marketing, and customer service. For instance, AI-powered chatbots and virtual assistants will provide more accurate and context-aware interactions, enhancing the customer experience and streamlining support functions..",

    },
    
    {
        "id": 5,
        "category": "Creative",
        "title": "Breaking: Major Tech Company Announces Game-Changing Innovation",
        "post": "Posted by  Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global",
        "image": "https://newsportal.electronthemes-ghost.com/content/images/size/w2000/2024/09/2149037906.jpg",
        "title1": "The Unveiling of a New Era",
        "image1": "https://images.unsplash.com/photo-1725615357444-6123528686cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8YWxsfDQzfHx8fHx8Mnx8MTcyNTg4MTQzNXw&ixlib=rb-4.0.3&q=80&w=1000",
        "semititle1": "In a highly anticipated event streamed live to millions of viewers worldwide, the CEO of the tech giant took the stage to reveal the company’s latest innovation. The atmosphere was electric as the audience, composed of industry experts, investors, and tech enthusiasts, waited with bated breath. The presentation began with a retrospective look at the company’s history of innovation, highlighting previous breakthroughs that had set new standards in the industry.",
        "quote": "But it was clear that this announcement was different. The company’s leader spoke passionately about the future and the responsibility of tech companies",

    },
    {
        "id": 6,
        "category": "Creative",
        "title": "Electric Car Revolutionize the Auto Industry",
        "post": "Posted by  Jamie Larison",
        "date": "Sep 05, 2024",
        "semiTitle": "New Electric Car Models Set to Revolutionize the Auto Industry",
        "image": "https://images.unsplash.com/photo-1603724223241-527d8009e029?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDR8fCUyMEVsZWN0cmljJTIwQ2FyfGVufDB8fHx8MTcyNTUzMjY0N3ww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Unveiling of a New Era",
        "semititle1": "The automotive industry is undergoing a monumental transformation, driven by advancements in electric vehicle (EV) technology, environmental concerns, and shifting consumer preferences. As the world moves towards greener and more sustainable transportation solutions, several new electric car models are poised to revolutionize the industry. This article delves into some of the most exciting new electric car models set to make a significant impact in the near future.",

    },
    {
        "id": 7,
        "category": "Creative",
        "title": "Top 10 Emerging Technologies to Watch",
        "post": "Posted by  Enamul Haque",
        "date": "Sep 05, 2024",
        "semiTitle": "Climate change is a pressing global challenge with far-reaching implications, affecting not only the environment but also economic activities and international trade. As the planet warms and extreme weather events become more frequent, the patterns and dynamics of global trade are being significantly altered. This article explores how climate change is impacting international trade, examining its effects on supply chains, trade patterns, and global markets, and discussing the strategies businesses and governments are adopting to adapt to these changes.",
        "image": "https://images.unsplash.com/photo-1678799200184-a813e6039df1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDE4fHx0ZWN8ZW58MHx8fHwxNzI1NTM3ODM3fDA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "Disruption of Supply Chains",

        "semititle1": "One of the most immediate and visible impacts of climate change on international trade is the disruption of supply chains. Extreme weather events, such as hurricanes, floods, and heatwaves, can cause significant damage to infrastructure, halt production, and delay shipments.",

    },
    {
        "id": 8,
        "category": "Creative",
        "title": "The Future of Quantum Computing: What to Expect",
        "post": "Posted by Walter White",
        "date": "Sep 05, 2024",
        "semiTitle": "As we approach 2024, businesses and entrepreneurs face a rapidly evolving landscape marked by technological advancements, shifting consumer expectations, and global economic changes. Staying ahead of these trends is crucial for strategic planning and maintaining a competitive edge. This article explores the top five business trends shaping 2024, providing insights into how these developments will influence the business world and what organizations need to do to adapt.",
        "image": "https://images.unsplash.com/photo-1667984390538-3dea7a3fe33d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDQ5fHxRdWFudHVtJTIwQ29tcHV0aW5nfGVufDB8fHx8MTcyNTU4Njg2NHww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "Artificial Intelligence and Automation",
        "semititle1": "Advances in AI technologies, such as machine learning and natural language processing, are enabling businesses to harness data more effectively. In 2024, we can expect AI to play a critical role in predictive analytics, personalized marketing, and customer service. For instance, AI-powered chatbots and virtual assistants will provide more accurate and context-aware interactions, enhancing the customer experience and streamlining support functions..",

    },
    {
        "id": 9,
        "category": "Creative",
        "title": "The Future of Quantum Computing: What to Expect",
        "post": "Posted by Walter White",
        "date": "Sep 05, 2024",
        "semiTitle": "As we approach 2024, businesses and entrepreneurs face a rapidly evolving landscape marked by technological advancements, shifting consumer expectations, and global economic changes. Staying ahead of these trends is crucial for strategic planning and maintaining a competitive edge. This article explores the top five business trends shaping 2024, providing insights into how these developments will influence the business world and what organizations need to do to adapt.",
        "image": "https://images.unsplash.com/photo-1667984390538-3dea7a3fe33d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDQ5fHxRdWFudHVtJTIwQ29tcHV0aW5nfGVufDB8fHx8MTcyNTU4Njg2NHww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "Artificial Intelligence and Automation",
        "semititle1": "Advances in AI technologies, such as machine learning and natural language processing, are enabling businesses to harness data more effectively. In 2024, we can expect AI to play a critical role in predictive analytics, personalized marketing, and customer service. For instance, AI-powered chatbots and virtual assistants will provide more accurate and context-aware interactions, enhancing the customer experience and streamlining support functions..",

    },
    {
        "id": 10,
        "category": "Lifestyle",
        "title": "How the Latest Political Decision Will Impact You",
        "post": "Posted by Emanuel Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In a world where economic stability is often viewed as a cornerstone of global prosperity, any sudden shift in the economic landscape sends ripples through financial markets, impacting businesses, governments, and individuals alike. Recently, a major economic shift has occurred, sparking widespread reactions from global markets. This sudden change, driven by a combination of geopolitical tensions, unexpected policy decisions, and shifting economic indicators, has left investors, analysts, and policymakers scrambling to assess the implications and adjust their strategies.",
        "image": "https://images.unsplash.com/photo-1554324282-930f8e66b77e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDQ0fHxwb2xpdGljYWwlMjB8ZW58MHx8fHwxNzI1ODYyMjA4fDA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 11,
        "category": "Fashion",
        "title": "Exclusive Interview: Industry Leader Shares Insights on Future Trends",
        "post": "Posted by Emanuel Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In a world where economic stability is often viewed as a cornerstone of global prosperity, any sudden shift in the economic landscape sends ripples through financial markets, impacting businesses, governments, and individuals alike. Recently, a major economic shift has occurred, sparking widespread reactions from global markets. This sudden change, driven by a combination of geopolitical tensions, unexpected policy decisions, and shifting economic indicators, has left investors, analysts, and policymakers scrambling to assess the implications and adjust their strategies.",
        "image": "https://images.unsplash.com/photo-1485125639709-a60c3a500bf1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDE1fHxGYXNoaW9ufGVufDB8fHx8MTcyNTg2MTgyM3ww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 12,
        "category": "Fashion",
        "title": "How to Incorporate High Fashion into Everyday Wear",
        "post": "Posted by Emanuel Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "Fashion Week 2024 has once again captured the imagination of style enthusiasts, industry insiders, and fashion lovers around the globe. As the most anticipated event in the fashion calendar, this year's Fashion Week didn't disappoint, showcasing an incredible array of stunning looks and introducing emerging trends that are set to dominate the fashion scene in the coming months. From bold color palettes and innovative fabrics to nostalgic throwbacks and futuristic designs, Fashion Week 2024 has offered a glimpse into the future of fashion, where creativity knows no bounds.",
        "image": "https://images.unsplash.com/photo-1505022610485-0249ba5b3675?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDM1fHxGYXNoaW9ufGVufDB8fHx8MTcyNTg4MDg5OXww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Return of Maximalism: Bold Colors and Prints",
        "semititle1": "One of the most prominent trends to emerge from Fashion Week 2024 is the return of maximalism. After years of minimalist and understated styles dominating the runways, designers are now embracing bold colors, vibrant prints, and eclectic patterns. This shift towards maximalism is a celebration of individuality and self-expression, encouraging fashion lovers to step out of their comfort zones and experiment with daring combinations.",

    },
    {
        "id": 13,
        "category": "Fashion",
        "title": "The Most Stunning Looks and Emerging Trends",
        "post": "Posted by Emanuel Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "Fashion Week 2024 has once again captured the imagination of style enthusiasts, industry insiders, and fashion lovers around the globe. As the most anticipated event in the fashion calendar, this year's Fashion Week didn't disappoint, showcasing an incredible array of stunning looks and introducing emerging trends that are set to dominate the fashion scene in the coming months. From bold color palettes and innovative fabrics to nostalgic throwbacks and futuristic designs, Fashion Week 2024 has offered a glimpse into the future of fashion, where creativity knows no bounds.",
        "image": "https://images.unsplash.com/photo-1589191799332-594675fa9d6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDE1fHxtYW4lMjBMb29rc3xlbnwwfHx8fDE3MjU4NjQ4OTl8MA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Return of Maximalism: Bold Colors and Prints",
        "semititle1": "One of the most prominent trends to emerge from Fashion Week 2024 is the return of maximalism. After years of minimalist and understated styles dominating the runways, designers are now embracing bold colors, vibrant prints, and eclectic patterns. This shift towards maximalism is a celebration of individuality and self-expression, encouraging fashion lovers to step out of their comfort zones and experiment with daring combinations.",

    },
    {
        "id": 14,
        "category": "Fashion",
        "title": "The Best Fashion Moments Captured Around the World",
        "post": "Posted by Jamie Larison",
        "date": "Sep 09, 2024",
        "semiTitle": "In a world where economic stability is often viewed as a cornerstone of global prosperity, any sudden shift in the economic landscape sends ripples through financial markets, impacting businesses, governments, and individuals alike. Recently, a major economic shift has occurred, sparking widespread reactions from global markets. This sudden change, driven by a combination of geopolitical tensions, unexpected policy decisions, and shifting economic indicators, has left investors, analysts, and policymakers scrambling to assess the implications and adjust their strategies.",
        "image": "https://images.unsplash.com/photo-1541495532687-d41ee8904943?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDIxfHxtYW4lMjBGYXNoaW9ufGVufDB8fHx8MTcyNTg4MTA0Nnww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 15,
        "category": "Design",
        "title": "Global Markets React to Sudden Economic Shift",
        "post": "Posted by   Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In a world where economic stability is often viewed as a cornerstone of global prosperity, any sudden shift in the economic landscape sends ripples through financial markets, impacting businesses, governments, and individuals alike. Recently, a major economic shift has occurred, sparking widespread reactions from global markets. This sudden change, driven by a combination of geopolitical tensions, unexpected policy decisions, and shifting economic indicators, has left investors, analysts, and policymakers scrambling to assess the implications and adjust their strategies.",
        "image": "https://images.unsplash.com/photo-1670121180583-39ab653a071c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDJ8fGdsb2JhbCUyMG1hcmtldHxlbnwwfHx8fDE3MjU4NjE3NTN8MA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 16,
        "category": "Design",
        "title": "In-Depth Analysis: The Rise of Electric Vehicles in 2024",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1670121180583-39ab653a071c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDJ8fGdsb2JhbCUyMG1hcmtldHxlbnwwfHx8fDE3MjU4NjE3NTN8MA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 17,
        "category": "Travel",
        "title": "Must-Visit Historic Sites Around the World",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1725017710297-d923d3102984?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8YWxsfDE4fHx8fHx8Mnx8MTcyNTUzNjA3OXw&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 18,
        "category": "Travel",
        "title": "Breaking: Natural Disaster Strikes, Thousands Affected",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1626990140776-407c6c0a1605?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjcmF0aXZlfGVufDB8fHx8MTcyNTg4MTkzOHww&ixlib=rb-4.0.3&q=80&w=1000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 19,
        "category": "Travel",
        "title": "Travel Hacks: How to Save Money on Your Next Adventure",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1725490854131-24f941fcf596?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8YWxsfDE1fHx8fHx8Mnx8MTcyNTUzNjA3OXw&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 20,
        "category": "Travel",
        "title": "Top 10 Hidden Travel Destinations",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1530789253388-582c481c54b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDR8fFRyYXZlbHxlbnwwfHx8fDE3MjU1ODg1MzF8MA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 21,
        "category": "Business",
        "title": "Top Tech Startups to Watch in the Next Quarter",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1719937050679-c3a2c9c67b0f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wxfDF8YWxsfDYxfHx8fHx8Mnx8MTcyNTUzODA4OXw&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 22,
        "category": "Business",
        "title": "Top 5 Business Trends Shaping 2024: What You Need to Know",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDI1fHxidXNpbmVzc3xlbnwwfHx8fDE3MjU1MjQzMDZ8MA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 23,
        "category": "Business",
        "title": "How Climate Change is Impacting International Trade",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDJ8fGludGVybmF0aW9uYWx8ZW58MHx8fHwxNzI1NTI0Njc0fDA&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },
    {
        "id": 24,
        "category": "Business",
        "title": "Global Economic Outlook: Key Insights from the Latest IMF Report",
        "post": "Posted by Enamul Haque",
        "date": "Sep 09, 2024",
        "semiTitle": "In an era defined by rapid technological advancements and constant innovation, one major tech company has once again captured global attention with the announcement of a groundbreaking development that promises to reshape industries and redefine the future of technology. This revolutionary innovation, which has been kept under wraps for years, has the potential to change the way we live, work, and interact with the world around us.",
        "image": "https://images.unsplash.com/photo-1553729459-efe14ef6055d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDd8fG1vbmV5fGVufDB8fHx8MTcyNTU4NjczNnww&ixlib=rb-4.0.3&q=80&w=2000",
        "title1": "The Catalyst for Change",
        "semititle1": "The sudden economic shift can be traced back to a series of events that, when combined, created a perfect storm of uncertainty. One of the primary catalysts was the unexpected announcement of a major policy change by a leading global economy. This policy, aimed at addressing long-standing economic imbalances, involved significant adjustments to interest rates, trade tariffs, and currency valuations. While the intent behind the policy was to stabilize the domestic economy, its ripple effects were felt far beyond the country's borders.",

    },

]